//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAMO
    {
        public System.DateTime HORA { get; set; }
        public decimal ID_CIUDAD { get; set; }
        public decimal valor { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual VUELO VUELO { get; set; }
    }
}
