//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASAJE
    {
        public string ID_VUELO { get; set; }
        public System.DateTime HORA { get; set; }
        public decimal N_ASIENTO { get; set; }
        public string RUT { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual VUELO VUELO { get; set; }
    }
}
